# Generated by Django 6.1 on 2026-08-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at'], 'permissions': [('moderate_recipe', 'Can edit and delete any recipe'), ('moderate_tag', 'Can manage tags'), ('moderate_ingredient', 'Can manage ingredients'), ('moderate_comment', 'Can delete any comment')]},
        ),
    ]
