# Generated by Django 6.1 on 2026-08-21 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
