# Generated by Django 6.1 on 2026-08-23 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=3000, validators=[django.core.validators.MaxLengthValidator(3000)]),
        ),
    ]
