# Generated by Django 6.1 on 2026-08-25 18:25

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_alter_comment_body"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # A no-op if the extension is already there — which it is for both
        # the persistent dev/prod database (db/init/01-create-app-user.sh
        # installs it as the postgres superuser, since that needs
        # database-level CREATE the app role isn't granted) and
        # pytest-django's throwaway test database (created BY the app role,
        # which makes it the owner and gives it that CREATE implicitly).
        TrigramExtension(),
        migrations.AddIndex(
            model_name="recipe",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("name"), name="gin_trgm_ops"
                ),
                name="recipe_name_trgm_idx",
            ),
        ),
    ]
